services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: entangled-body-api
    working_dir: /app/apps/api
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
